service: serverless-send-emails-api

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: default
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: <YOUR_STREAM_ARN>
    - Effect: Allow
      Action:
        - "ses:*"
      Resource: "*"

functions:
  sendEmail:
    handler: emails/send.send
    events:
      - stream: <YOUR_STREAM_ARN>
