service: serverless-static-website

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: default
  stage: dev

plugins:
  - serverless-finch

custom:
  client:
    bucketName: serverless-static-website

